databases:
  - name: rails_recipes
    databaseName: rails_recipes_test
    user: postgresql

services:
  - type: web
    name: rails_recipes
    env: ruby
    buildCommand: "./rails_recipes/bin/render-build.sh"
    startCommand: "bundle exec puma -C rails_recipes/config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false